server:
  port: 8401
spring:
  application:
    name: cloud-platform-auth
  redis:
    host: localhost
    port: 6379
    database: 1
    password: saiyau
    timeout: 3000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxactive: 64
        # 连接池中的最大空闲连接
        maxidle: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxwait: -1
        # 连接池中的最小空闲连接
        minidle: 1
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  okhttp:
    enabled: true
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false