server:
  port: 8401
spring:
  application:
    name: cloud-platform-auth
  redis:
    host: localhost
    port: 6379
    database: 1
    password: saiyau
    timeout: 3000ms
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  okhttp:
    enabled: true