server:
  port: 8201
spring:
  application:
    name: cloud-platform-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: cloud-platform-auth
          uri: lb://cloud-platform-auth #认证中心
          predicates:
            - Path=/cloud-platform-auth/**
          filters:
            - StripPrefix=1
        - id: cloud-platform-admin
          uri: lb://cloud-platform-admin #后台管理
            predicates:
              - Path=/cloud-platform-admin/**
            filters:
              - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    password: saiyau
    timeout: 3000ms
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        maxactive: 64
        # 连接池中的最大空闲连接
        maxidle: 64
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxwait: -1
        # 连接池中的最小空闲连接
        minidle: 1
# security:
#   oauth2:
#     resourceserver:
#       jwt:
#         jwk-set-uri: 'http://localhost:8201/cloud-platform-auth/publicKey' #配置RSA的公钥访问地址

#配置白名单路径(无需认证登录)
secure:
  ignore:
    urls:
      - /cloud-platform-auth/oauth/token/**
      - /webjars/**
      - /doc.html
      - /swagger-resources/**
      - /swagger/**
      - /*/v2/api-docs
      - /actuator/**
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always